version: "3.8"
services:
  my-running-php:
    build: .
    networks:
      - lamp
    volumes:
      - /home/richard/work/my_docker_test:/var/www/html
    ports:
      - "8080:80"
  my-running-mysql:
    image: "mysql:5.7"
    networks:
      - lamp
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  my-running-amqp:
    image: "rabbitmq:3.7-management"
    networks:
      - lamp
networks:
  lamp: