FROM php:7.4-cli

COPY . /app

WORKDIR /app

RUN apt-get update \
    && apt-get install -y librabbitmq-dev \
    && printf "\n" | pecl install amqp \
    && docker-php-ext-configure pdo_mysql \
    && docker-php-ext-install -j$(nproc) pdo_mysql \
    && docker-php-ext-enable amqp