version: "3.8"
networks:
  lamp:
    name: lamp
    driver: bridge
services:
  my-running-php:
    container_name: my-running-php
    image: "rthompson961/my-php-app:latest"
    networks:
      - lamp
    #volumes:
      #- /home/richard/work/my_docker_test:/var/www/html
    #ports:
      #- "8080:80"
    environment:
      - DATABASE_URL=mysql://root:root@my-running-mysql:3306/dockertest?serverVersion=5.7
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@my-running-amqp:5672/%2f/messages
    depends_on:
      - my-running-mysql
      - my-running-amqp
  my-running-mysql:
    container_name: my-running-mysql
    image: "mysql:5.7"
    networks:
      - lamp
    #ports:
      #- "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  my-running-amqp:
    container_name: my-running-amqp
    image: "rabbitmq:3.7-management"
    networks:
      - lamp
    #ports:
      #- "5672:5672"